error: An error occurred: Out of range value for column 'phonenumber' at row 1 {"name":"SequelizeDatabaseError","original":{"code":"ER_WARN_DATA_OUT_OF_RANGE","errno":1264,"parameters":["Vinay",9618421328,"kvk.9618@gmail.com","$2b$10$834J1sLW3e/QytwvdZISXe6iXSAv0MUfbs95QSIMlwuIuIB.Iu/HG","2023-07-13 11:26:27","2023-07-13 11:26:27"],"sql":"INSERT INTO `signups` (`id`,`username`,`phonenumber`,`email`,`password`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?,?,?,?,?);","sqlMessage":"Out of range value for column 'phonenumber' at row 1","sqlState":"22003"},"parameters":["Vinay",9618421328,"kvk.9618@gmail.com","$2b$10$834J1sLW3e/QytwvdZISXe6iXSAv0MUfbs95QSIMlwuIuIB.Iu/HG","2023-07-13 11:26:27","2023-07-13 11:26:27"],"parent":{"code":"ER_WARN_DATA_OUT_OF_RANGE","errno":1264,"parameters":["Vinay",9618421328,"kvk.9618@gmail.com","$2b$10$834J1sLW3e/QytwvdZISXe6iXSAv0MUfbs95QSIMlwuIuIB.Iu/HG","2023-07-13 11:26:27","2023-07-13 11:26:27"],"sql":"INSERT INTO `signups` (`id`,`username`,`phonenumber`,`email`,`password`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?,?,?,?,?);","sqlMessage":"Out of range value for column 'phonenumber' at row 1","sqlState":"22003"},"sql":"INSERT INTO `signups` (`id`,`username`,`phonenumber`,`email`,`password`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?,?,?,?,?);","stack":"Error\n    at Query.run (/media/vinay/CC4A7C094A7BEE98/ChatConnect/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)\n    at /media/vinay/CC4A7C094A7BEE98/ChatConnect/node_modules/sequelize/lib/sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async MySQLQueryInterface.insert (/media/vinay/CC4A7C094A7BEE98/ChatConnect/node_modules/sequelize/lib/dialects/abstract/query-interface.js:308:21)\n    at async model.save (/media/vinay/CC4A7C094A7BEE98/ChatConnect/node_modules/sequelize/lib/model.js:2490:35)\n    at async signup.create (/media/vinay/CC4A7C094A7BEE98/ChatConnect/node_modules/sequelize/lib/model.js:1362:12)\n    at async exports.signupdetails (/media/vinay/CC4A7C094A7BEE98/ChatConnect/controllers/signup.js:20:18)"}
error: An error occurred: Out of range value for column 'phonenumber' at row 1 {"name":"SequelizeDatabaseError","original":{"code":"ER_WARN_DATA_OUT_OF_RANGE","errno":1264,"parameters":["Vinay",9618421328,"kvk.9618@gmail.com","$2b$10$fnfEPfuUd8Sg0cS1HJYqKu83G.0bzHWAOt8nOY4PqGp7empL49nX6","2023-07-13 11:31:37","2023-07-13 11:31:37"],"sql":"INSERT INTO `signups` (`id`,`username`,`phonenumber`,`email`,`password`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?,?,?,?,?);","sqlMessage":"Out of range value for column 'phonenumber' at row 1","sqlState":"22003"},"parameters":["Vinay",9618421328,"kvk.9618@gmail.com","$2b$10$fnfEPfuUd8Sg0cS1HJYqKu83G.0bzHWAOt8nOY4PqGp7empL49nX6","2023-07-13 11:31:37","2023-07-13 11:31:37"],"parent":{"code":"ER_WARN_DATA_OUT_OF_RANGE","errno":1264,"parameters":["Vinay",9618421328,"kvk.9618@gmail.com","$2b$10$fnfEPfuUd8Sg0cS1HJYqKu83G.0bzHWAOt8nOY4PqGp7empL49nX6","2023-07-13 11:31:37","2023-07-13 11:31:37"],"sql":"INSERT INTO `signups` (`id`,`username`,`phonenumber`,`email`,`password`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?,?,?,?,?);","sqlMessage":"Out of range value for column 'phonenumber' at row 1","sqlState":"22003"},"sql":"INSERT INTO `signups` (`id`,`username`,`phonenumber`,`email`,`password`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?,?,?,?,?);","stack":"Error\n    at Query.run (/media/vinay/CC4A7C094A7BEE98/ChatConnect/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)\n    at /media/vinay/CC4A7C094A7BEE98/ChatConnect/node_modules/sequelize/lib/sequelize.js:315:28\n    at async MySQLQueryInterface.insert (/media/vinay/CC4A7C094A7BEE98/ChatConnect/node_modules/sequelize/lib/dialects/abstract/query-interface.js:308:21)\n    at async model.save (/media/vinay/CC4A7C094A7BEE98/ChatConnect/node_modules/sequelize/lib/model.js:2490:35)\n    at async signup.create (/media/vinay/CC4A7C094A7BEE98/ChatConnect/node_modules/sequelize/lib/model.js:1362:12)\n    at async exports.signupdetails (/media/vinay/CC4A7C094A7BEE98/ChatConnect/controllers/signup.js:20:18)"}
error: An error occurred: notNull Violation: messages.message cannot be null,
notNull Violation: messages.userId cannot be null {"errors":[{"instance":{"createdAt":"2023-07-14T03:59:21.022Z","id":null,"updatedAt":"2023-07-14T03:59:21.022Z"},"message":"messages.message cannot be null","origin":"CORE","path":"message","type":"notNull Violation","validatorArgs":[],"validatorKey":"is_null","validatorName":null,"value":null},{"instance":{"createdAt":"2023-07-14T03:59:21.022Z","id":null,"updatedAt":"2023-07-14T03:59:21.022Z"},"message":"messages.userId cannot be null","origin":"CORE","path":"userId","type":"notNull Violation","validatorArgs":[],"validatorKey":"is_null","validatorName":null,"value":null}],"name":"SequelizeValidationError","stack":"SequelizeValidationError: notNull Violation: messages.message cannot be null,\nnotNull Violation: messages.userId cannot be null\n    at InstanceValidator._validate (/media/vinay/CC4A7C094A7BEE98/ChatConnect/node_modules/sequelize/lib/instance-validator.js:50:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async InstanceValidator._validateAndRunHooks (/media/vinay/CC4A7C094A7BEE98/ChatConnect/node_modules/sequelize/lib/instance-validator.js:60:7)\n    at async InstanceValidator.validate (/media/vinay/CC4A7C094A7BEE98/ChatConnect/node_modules/sequelize/lib/instance-validator.js:54:12)\n    at async model.save (/media/vinay/CC4A7C094A7BEE98/ChatConnect/node_modules/sequelize/lib/model.js:2426:7)\n    at async messages.create (/media/vinay/CC4A7C094A7BEE98/ChatConnect/node_modules/sequelize/lib/model.js:1362:12)\n    at async exports.chatdetails (/media/vinay/CC4A7C094A7BEE98/ChatConnect/controllers/chat.js:11:18)"}
